import Link from 'next/link'
import React from 'react'

type ContainerProps = unknown

export type Props = unknown

export const Component: React.FC<Props> = () => (
  <main>
    <article className="text-center">
      <h1 className="text-3xl font-bold">My Blog</h1>
      <p className="py-2">This page is generated by SSG.</p>
    </article>

    <ul className="my-4 flex justify-center space-x-2">
      <li>
        <Link href="/i18n-blog" locale="en-US">
          <a className="text-blue-600">English</a>
        </Link>
      </li>
      <li>
        <Link href="/i18n-blog" locale="ja-JP">
          <a className="text-blue-600">日本語</a>
        </Link>
      </li>
    </ul>
  </main>
)

const Container: React.FC<ContainerProps> = () => {
  return <Component />
}

export default Container
