import Link from 'next/link'
import React from 'react'

type ContainerProps = unknown

export type Props = unknown

export const Component: React.FC<Props> = () => (
  <div className="text-center">
    <h1 className="text-2xl font-bold">My Blog</h1>
    <p className="py-2">This page is generated by SSG.</p>
    <p className="py-2">
      If you want to read this page in Japanese, just click{' '}
      <Link href="/i18n-blog" locale="ja-JP">
        <a className="text-blue-600">日本語 ver</a>
      </Link>
      .
    </p>
  </div>
)

const Container: React.FC<ContainerProps> = () => {
  return <Component />
}

export default Container
