import Link from 'next/link'
import React from 'react'

type Blog = { title: string; body: string; appendix: string }

type Props = { blog: Blog; slug: string }

const Component: React.FC<Props> = (props) => (
  <main className="mx-auto text-center max-w-md">
    <article>
      <h1 className="text-3xl font-bold">{props.blog.title}</h1>
      <p className="py-2">{props.blog.body}</p>

      <p>
        {props.blog.appendix} 👉{' '}
        <a href="https://nextjs.org/docs/advanced-features/i18n-routing" target="_blank" rel="noopener noreferrer">
          <em className="text-blue-600">Internationalized Routing</em>
        </a>
      </p>
    </article>

    <ul className="my-8 flex justify-center space-x-2">
      <li>
        <Link href={`/i18n-blog/${props.slug}`} locale="en-US">
          <a className="text-blue-600">English</a>
        </Link>
      </li>
      <li>
        <Link href={`/i18n-blog/${props.slug}`} locale="ja-JP">
          <a className="text-blue-600">日本語</a>
        </Link>
      </li>
    </ul>
  </main>
)

export const getStaticProps = (props) => {
  let blog: Blog | null

  switch (props.locale) {
    case 'ja-JP':
      blog = {
        title: 'ブログ記事',
        body: 'このページはSSGで生成されました。',
        appendix: 'Next.js の i18n の機能について知りたい場合は、公式ドキュメントをご覧ください。',
      }
      break
    default:
      blog = {
        title: 'My Blog',
        body: 'This page is generated by SSG.',
        appendix: 'Want to know more about Next.js i18n feature? Just check out',
      }
      break
  }
  return {
    props: { blog, slug: props.params.slug },
  }
}

export const getStaticPaths = () => {
  const locales = ['en-US', 'ja-JP']
  const slug = 'first-blog'
  const paths = locales.map((locale) => ({ params: { slug }, locale }))

  return {
    paths,
    fallback: false,
  }
}

export default Component
